language: cpp
matrix:
  include:
    - os: linux
      compiler: "g++-4.9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - g++-4.9
            - cmake
            - cmake-data
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
    - os: osx
      compiler: "clang"

before_install:
  - CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
    mkdir -p ~/julia
    curl -A "$CURL_USER_AGENT" -s -L --retry 7 'https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6-latest-linux-x86_64.tar.gz' | tar -C ~/julia -x -z --strip-components=1 -f -

install:
  - mkdir build
  - cd build
  - cmake -DJulia_EXECUTABLE=$HOME/julia/bin/julia ..
  - cmake --build . --config Debug --target all

script:
  ctest -V

notifications:
  email: true
