language: julia
os: 
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - rr
env:
  CXX=g++-7
julia:
  - nightly
notifications:
  email: false

script:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then unset CXX; fi
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/install -DAPPEND_OVERRIDES_TOML=ON -DCMAKE_BUILD_TYPE=Release ..
  - VERBOSE=ON cmake --build . --config Debug --target install
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then ln -s libcxxwrap_julia.0.8.2.dylib lib/libcxxwrap_julia.0.8.0.dylib; fi
  - julia -e 'using Pkg; pkg"add https://github.com/barche/libcxxwrap_julia_jll.jl.git"; pkg"add CxxWrap#master"; using CxxWrap'
  - sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'.
  - rr record ctest -V
  - cd ../testlib-builder
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$HOME/install ../src/testlib
  - cmake --build . --config Release
